name: Feature / Change Request
description: File a feature or change request
title: 'Short description of the feature or change'
labels: ['enhancement', 'triage']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the change you would like to see?'
    validations:
      required: true
  - type: textarea
    id: intended-outcome
    attributes:
      label: Intended Outcome
      description: What is the intended outcome of this change?
    validations:
      required: false
  - type: textarea
    id: how-will-it-work
    attributes:
      label: How will it work?
      description: How will this change work?
    validations:
      required: false
