name: Roadmap Item
description: Suggest a new item for the project roadmap.
labels: ['triage', 'roadmap']
type: Task
body:
  - type: textarea
    id: value
    attributes:
      label: Value Prop
      description: What is the value proposition of this roadmap item?
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Expected Outcome
      description: What is the expected outcome of this roadmap item?
    validations:
      required: true
